Allow secrets management without env activated

diff --git a/bin/vault-secrets-download b/bin/vault-secrets-download
--- a/bin/vault-secrets-download
+++ b/bin/vault-secrets-download
@@ -4,6 +4,19 @@ set -e
 
 source $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/../src/vars.sh
 
+if [[ -f ${DEVOPS_CONFIG_FILE} ]]; then
+    source ${DEVOPS_CONFIG_FILE}
+fi
+
+if [[ ${VAULT_ADDR} == "https://server-url:8080" ]] || [[ ${VAULT_ADDR} == "" ]]; then
+    log_error "[hashicorp_vault] ERROR Config not found!"
+    exit 1
+fi
+
+if [[ ${VAULT_TOKEN} == "" ]]; then
+    source ${DEVOPS_SRC_DIR}/hashicorp_vault/get-token.sh
+fi
+
 log_info "[hashicorp_vault] Downloading secrets..."
 
 # Get files from Hashicorp Vault
diff --git a/bin/vault-secrets-upload b/bin/vault-secrets-upload
--- a/bin/vault-secrets-upload
+++ b/bin/vault-secrets-upload
@@ -4,6 +4,19 @@ set -e
 
 source $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/../src/vars.sh
 
+if [[ -f ${DEVOPS_CONFIG_FILE} ]]; then
+    source ${DEVOPS_CONFIG_FILE}
+fi
+
+if [[ ${VAULT_ADDR} == "https://server-url:8080" ]] || [[ ${VAULT_ADDR} == "" ]]; then
+    log_error "[hashicorp_vault] ERROR Config not found!"
+    exit 1
+fi
+
+if [[ ${VAULT_TOKEN} == "" ]]; then
+    source ${DEVOPS_SRC_DIR}/hashicorp_vault/get-token.sh
+fi
+
 # For each file in 'DEVOPS_SECRETS_DIR'
 SECRETS_FILES=''
 for FILE_PATH in "${DEVOPS_SECRETS_DIR}"/* ; do
@@ -16,4 +29,4 @@ done
 
 # Upload all files to the Vault
 log_info "[hashicorp_vault] Uploading secrets..."
-vault kv put ${VAULT_KV_PATH}/${VAULT_SECRET_NAME} ${SECRETS_FILES}
+${DEVOPS_ENV_DIR}/bin/vault kv put ${VAULT_KV_PATH}/${VAULT_SECRET_NAME} ${SECRETS_FILES}
